### ISSUE TITLE
Combine artifacts for each compiler into a single artifact

### ISSUE THREAD

**Issue by sei-eschwartz** [sei-eschwartz/buildexes#1]
Instead of defining the jobs directly, we can make a variable that is a list of jobs, and then turn them into jobs as [here](https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/each-expression.md):
``` yaml
parameters:
  jobs: []

jobs:
- job: CredScan                       # Cred scan first
  pool: MyCredScanPool
  steps:
  - task: MyCredScanTask@1
- ${{ each job in parameters.jobs }}: # Then each job
  - ${{ each pair in job }}:          # Insert all properties other than "dependsOn"
      ${{ if ne(pair.key, 'dependsOn') }}:
        ${{ pair.key }}: ${{ pair.value }}
    dependsOn:                        # Inject dependency
    - CredScan
    - ${{if job.dependsOn}}:            
      - ${{ job.dependsOn }}
``` 

Then we can create a new stage/job that depends on those jobs and uses an each loop to download the artifacts and make an uber artifact.
